site_name: ReserveTonLogis
nav:
  - Gestion des Réservations: /#gestion-des-réservations
  - Tarification Dynamique: /#tarification-dynamique
  - Galerie Photos: /#galerie-photos
  - Activités Proposées: /#activités-proposées
  - Météo Locale: /#météo-locale
  - Itinéraires et Bornes Électriques: /#itinéraires-et-bornes-électriques
  - Calendrier de Réservation: /#calendrier-de-réservation
  - Connexion/Inscription: /#connexioninscription
  - Contacter le Propriétaire: /#contacter-le-propriétaire
  - Données Personnelles: /#données-personnelles

theme: readthedocs